config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # devise_for :users

  root to: "pages#swipe"



  resources :profiles, only: [:show]
  # get "/profile/:id", to: "profiles#show", as: "profile"

  get "/matches", to: "matches#matches"
# ---
  patch 'update_radius', to: 'pages#update_radius'
# ---
  resources :users, only: [:show]
  resources :matches, only: [:destroy]
  resources :vinyles, except: [:index] do
    resources :matches, only: [:create]
  end
  resources :matches, only: [:show] do
    resources :messages, only: :create
  end

  resources :user_likes, only: [:create]
  resources :user_dislikes, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @vinyles = @user.vinyles
  end
end

app/views/profiles/show.html.erb
<div class="container position-relative mt-3">
  <div class="position-relative w-100">
    <%= link_to image_tag("back.png", width: "40px", height: "40px"), root_path, class: "position-absolute start-0 ms-3" %>
    <%= link_to image_tag("log_out.png", width: "40px", height: "40px"), destroy_user_session_path, data: { turbo_method: :delete }, class: "position-absolute end-0 me-3" %>
  </div>

  <div class="profile row justify-content-center baseline">
    <%# <% username = @user.email.split('@').first %>
    <% username = @user.nickname %>
    <%= cl_image_tag @user.photo.key, class:"avatar-large", alt:"User profile" %>
    <h1 class="text-center mt-2 text-capitalize"><%= username %></h1>
  </div>

  <hr class="mb-5">

  <div class="profile-card">
    <% @vinyles.each do |vinyle| %>
    <%= link_to vinyle_path(vinyle) do %>
          <div class="vinyles-card d-flex justify-content-between align-items-center mb-4 me-3">
            <%= cl_image_tag vinyle.photo.key, class:"avatar", alt:"image-vinyles" %>
            <div class="vinyle-info">
              <h2><%= vinyle.title %></h2>
              <p><%= vinyle.description %></p>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

<div class="container d-flex justify-content-center mt-5">
  <%= link_to new_vinyle_path, class: "btn-add" do %>
    <i class="fa-solid fa-plus"></i>
  <% end %>
</div>