config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # devise_for :users

  root to: "pages#swipe"



  resources :profiles, only: [:show]
  # get "/profile/:id", to: "profiles#show", as: "profile"

  get "/matches", to: "matches#matches"
# ---
  patch 'update_radius', to: 'pages#update_radius'
# ---
  resources :users, only: [:show]
  resources :matches, only: [:destroy]
  resources :vinyles, except: [:index] do
    resources :matches, only: [:create]
  end
  resources :matches, only: [:show] do
    resources :messages, only: :create
  end

  resources :user_likes, only: [:create]
  resources :user_dislikes, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/vinyle.rb
class Vinyle < ApplicationRecord
  belongs_to :user
  has_many :primary_vinyles, class_name: "Match", foreign_key: "vinyle1_id", dependent: :destroy
  has_many :secondary_vinyles, class_name: "Match", foreign_key: "vinyle2_id", dependent: :destroy
  has_many :user_likes, dependent: :destroy
  has_many :user_dislikes, dependent: :destroy

  has_one_attached :photo
  # validates :photo, content_type: ['image/png', 'image/jpg', 'image/jpeg']

  validates :quality, presence: true
  validates :description, presence: { message: "Ne peut pas être vide" }
  validates :title, presence: { message: "Ne peut être vide" }
  validates :artist, presence: { message: "Ne peut être vide" }
  validates :year, presence: { message: "Ne peut être vide" }
  validates :photo, presence: { message: "Ne peut être vide" }
  # TODO : Available

  scope :not_liked_or_disliked_by, lambda { |user|
    # retourne un array avec tous les users dans le périmètre
    users_in_radius = User.near([user.latitude, user.longitude], user.search_radius)

    # users_id_in_radius = users_in_radius.map(&:id)

    # retourne tous les vinyles des users qui sont dans le périmètres
    # vinyles_in_radius = Vinyle.where(user_id: users_id_in_radius)

    current_user_vinyles_ids = Vinyle.where(user_id: user).pluck(:id)
    liked_ids = UserLike.where(user: user).pluck(:vinyle_id)
    disliked_ids = UserDislike.where(user: user).pluck(:vinyle_id)
    where(user_id: users_in_radius.map(&:id)).where.not(id: liked_ids + disliked_ids + current_user_vinyles_ids)
    # where.not(user: user).where.not(id: liked_ids + disliked_ids)

    # nouvelle ligne
    # where(id: users_in_radius).where.not(user: user).where.not(id: liked_ids + disliked_ids)
  }
end

app/controllers/vinyles_controller.rb
class VinylesController < ApplicationController
  before_action :set_vinyle, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]


  def new
    @vinyle = Vinyle.new
  end

  def show
    @vinyle = Vinyle.find(params[:id])
    @match = Match.new
  end

  def create
    @vinyle = Vinyle.new(vinyle_params)
    @vinyle.user = current_user
    if @vinyle.save
      redirect_to vinyle_path(@vinyle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @vinyle.update(vinyle_params)
      redirect_to @vinyle
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @vinyle = Vinyle.find(params[:id])
    
    @vinyle.destroy
    redirect_to profile_path(current_user)
  end

  private

  def set_vinyle
    @vinyle = Vinyle.find(params[:id])
  end

  def vinyle_params
    params.require(:vinyle).permit(:title, :artist, :year, :description, :quality, :available, :photo)
  end

  def authorize_user!
    unless @vinyle.user == current_user
      redirect_to root_path, alert: "Tu n'as pas l'autorisation d'effectuer cette action."
    end
  end

end

app/views/vinyles/edit.html.erb
<div class="container position-relative mt-3">


<%= link_to image_tag("back.png", width: "40px", height: "40px"), profile_path(current_user), class: "position-relative start-0 ms-3" %>

  <div class="container">
    <h1 class='mt-5 mb-4' style="font-size: 40px;">Modifie ton Vinyle</h1>
    <%= simple_form_for @vinyle, local: true do |f| %>
      <%= f.input :title, placeholder: "Titre", label: false, input_html: { class: 'form-field mb-4' } %>
      <%= f.input :artist, placeholder: "Artiste", label: false,  input_html: { class: 'form-field mb-4' } %>
      <%= f.input :year, placeholder: "Année", label: false, input_html: { class: 'form-field mb-4' } %>
      <%= f.input :description, placeholder: "Description", label: false, input_html: { class: 'form-field mb-4' } %>

      <%= f.input :photo, as: :file, input_html: { class: 'form-field mb-4', accept: "image/png,image/jpeg,image/jpg" }, label: false %>
      <%= f.input :quality, as: :radio_buttons, collection: [['Neuf', 'Neuf'] ,['Occasion', 'Occasion']], label_method: :second, value_method: :first, label: false, wrapper: :horizontal_collection_inline %>

      <div class='d-flex justify-content-center mt-5 gap-4'>
      <%= link_to "Annuler", profile_path(current_user), class: "btn btn-lightred" %>
      <%= f.submit value: "Valider", class:'btn-lavandia'%>
      </div>
    <% end %>
  </div>
</div>

app/views/vinyles/new.html.erb
<div class="container position-relative mt-3">


<%= link_to image_tag("back.png", width: "40px", height: "40px"), root_path, class: "position-relative mb-3" %>


  <div class="container">
    <h1 class='mt-5 mb-4' style="font-size: 40px;">Ajoute ton Vinyle</h1>
    <%= simple_form_for @vinyle, local: true do |f| %>
      <%= f.input :title, placeholder: "Titre", label: false, input_html: { class: 'form-field mb-4' } %>
      <%= f.input :artist, placeholder: "Artiste", label: false,  input_html: { class: 'form-field mb-4' } %>
      <%= f.input :year, placeholder: "Année",
       as: :select, collection: (1950..Time.now.year).to_a.reverse, input_html: { class: 'form-field mb-4' },
       label: false %>
      <%= f.input :description, placeholder: "Description", label: false, input_html: { class: 'form-field mb-4' } %>

      <%= f.input :photo, as: :file, input_html: { class: 'form-field mb-4', accept: "image/png,image/jpeg,image/jpg" }, label: false %>
      <%= f.input :quality, as: :radio_buttons, collection: [['Neuf', 'Neuf'] ,['Occasion', 'Occasion']], label_method: :second, value_method: :first, label: false, wrapper: :horizontal_collection_inline %>

      <div class='d-flex justify-content-center mt-5 gap-4'>
      <%= link_to "Annuler", profile_path(current_user), class: "btn btn-lightred" %>
      <%= f.submit value: "Ajouter", class:'btn-lavandia'%>
      </div>
    <% end %>
  </div>
</div>

app/views/vinyles/show.html.erb
<div class="container">
  <%= link_to profile_path(@vinyle.user), class: "position-absolute start-0 ms-3 z-index-absolute" do %>
   <%= image_tag("back.png", width: "40px", height: "40px") %>
  <% end %>


  <div class="container position-relative mt-3 d-flex flex-column gap-5">

  <div class="vinyle-card pb-5">
    <div class="vinyle-image-container">
      <%= cl_image_tag @vinyle.photo.key, class: "vinyle-image" %>
    </div>
    <div><h1><%= @vinyle.title %> - <%= @vinyle.artist %></h1></div>
    <div class="container d-flex justify-content-start">
      <div class="vinyle-details mt-4">
        <h2><strong>Année:</strong></h2><p> <%= @vinyle.year %></p>
        <h2><strong>Description:</strong></h2><p> <%= @vinyle.description %></p>
        <h2><strong>Etat du vinyle:</strong></h2><p> <%= @vinyle.quality %></p>
      </div>
    </div>
  </div>
</div>

<div class="button-container d-flex justify-content-center gap-4">
  <% if @vinyle.user == current_user %>
    <%= link_to "Supprimer", vinyle_path(@vinyle), data: { turbo_method: :delete, turbo_confirm: "Es-tu sûr de vouloir supprimer ce vinyle ?" }, class: "btn btn-lightred" %>
    <%= link_to "Modifier", edit_vinyle_path(@vinyle), class: "btn btn-lavandia" %>
  <% end %>
</div>

</div>