config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # devise_for :users

  root to: "pages#swipe"



  resources :profiles, only: [:show]
  # get "/profile/:id", to: "profiles#show", as: "profile"

  get "/matches", to: "matches#matches"
# ---
  patch 'update_radius', to: 'pages#update_radius'
# ---
  resources :users, only: [:show]
  resources :matches, only: [:destroy]
  resources :vinyles, except: [:index] do
    resources :matches, only: [:create]
  end
  resources :matches, only: [:show] do
    resources :messages, only: :create
  end

  resources :user_likes, only: [:create]
  resources :user_dislikes, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :vinyle1, class_name: "Vinyle", foreign_key: "vinyle1_id"
  belongs_to :vinyle2, class_name: "Vinyle", foreign_key: "vinyle2_id"
  has_many :messages, dependent: :destroy

  validates :vinyle1_id, uniqueness: { scope: :vinyle2_id }
  validates :vinyle2_id, uniqueness: { scope: :vinyle1_id }

  scope :pair, lambda { |vinyle1, vinyle2|
    # regarder dans tous les matchs si il y a deja un match
    # entre les deux vinyles
    # Find matches where either:
    # 1. vinyle1 belongs to user1 and vinyle2 belongs to user2
    # 2. vinyle1 belongs to user2 and vinyle2 belongs to user1
    user1_vinyles = vinyle1.user.vinyles.pluck(:id)
    user2_vinyles = vinyle2.user.vinyles.pluck(:id)
    where("(vinyle1_id IN (?) AND vinyle2_id IN (?))", user1_vinyles, user2_vinyles)
  }
end

app/controllers/concerns/matches_controller.rb
class BookingsController < ApplicationController
  def create
    @vinyle = Vinyle.find(params[:vinyle_id])
    @match = Match.new(match_params)
    @match.vinyle = @vinyle
    @match.user = current_user
    if @match.save
      redirect_to @vinyle
    else
      render "vinyles/show"
    end
  end

  def show
    @match = Match.find(params[:id])
    @message = Message.new
  end

  private

  def match_params
    params.require(:match).permit(:date)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def create
    @vinyle = Vinyle.find(params[:vinyle_id])
    @match = Match.new(match_params)
    @match.vinyle = @vinyle
    @match.user = current_user
    if @match.save
      redirect_to @vinyle
    else
      render "vinyles/show"
    end
  end

  def matches
    @vinyles = Vinyle.where(user: current_user)
    @matches = Match.where(vinyle1: @vinyles).or(Match.where(vinyle2: @vinyles))

  end

  def show
    @match = Match.find(params[:id])
    @messages = @match.messages
    @message = Message.new
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
  end

  private

  def match_params
    params.require(:match).permit(:date)
  end
end

app/views/matches/matches.html.erb
<div class="container position-relative mt-3">
  <%= link_to image_tag("back.png", width: "40px", height: "40px"), root_path, class: "position-absolute start-0 ms-3" %>
  <h1 class="text-center m-0">Side.B</h1>
</div>

<% if @matches.any? %>
  <h2 class= "text-start mt-4 ms-2" style="font-size: 16px; font-style: italic;">Nouveaux échanges</h2>

  <div class="matches-bar">
  <% @matchs_no_messages = @matches.reject {|match| match.messages.any?} %>
    <% @matchs_no_messages.each_with_index do |match, index| %>
      <%= link_to match do %>
        <% other_vinyle = match.vinyle1.user != current_user ? match.vinyle1 : match.vinyle2 %>
        <%= cl_image_tag other_vinyle.photo.key, class:"match-bubble" %>
      <% end %>
    <% end %>
  </div>

  <h2 class="text-start mt-4 mb-3 ms-2" style="font-size: 16px; font-style: italic;">Messages</h2>

  <div class="matches-details container d-grid gap-3">

  <% @matches_messages = @matches.select {|match| match.messages.any?} %>

    <% @matches_messages.each do |match| %>
      <%= link_to match do %>
        <div class="d-flex align-items-center">

          <% vinyle = current_user == match.vinyle1.user ? match.vinyle2 : match.vinyle1 %>
          <% other_vinyle = match.vinyle1.user != current_user ? match.vinyle1 : match.vinyle2 %>
          <% username = vinyle.user.email.split('@').first %>

          <div class="avatar">
            <%= cl_image_tag other_vinyle.photo.key, class:"avatar" %>
          </div>

          <div class="d-flex flex-column ms-2">
            <p class="fw-bold mb-0"><%= username %></p>
            <p class='mb-0'>
              <%= match.messages.last.content if match.messages.any? %>
            </p>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= render "shared/navbar" %>

app/views/matches/matchs.html.erb
<% if @matches.any? %>
  <h2>Your matches</h2>
  <ul>
    <% @matches.each do |match| %>
      <li><%= link_to match.vinyle1.title, match %></li>
    <% end %>
  </ul>
<% end %>

app/views/matches/show.html.erb
<div class="d-flex flex-column justify-content-between vh-100">


  <div class="top-chat-page mt-4">
    <div class="container position-relative d-flex justify-content-between index p-2">

      <%= link_to image_tag("back.png", width: "40px", height: "40px"), matches_path, class: "start-0 ms-3 z-3" %>
      <%# Bouton exchange validate %>
      <%= button_to "Valider l'échange", match_path(@match), class:"me-3 btn-lavandia w-100", data: {bs_toggle:"modal", bs_target:"#validateModal"}, method: :delete, confirm: "te", turbo: false  %>
      <%# <button type="button" class="me-3 btn-lavandia" data-bs-toggle="modal" data-bs-target="#validateModal">
        Valider l'échange
      </button> %>
      <%# Bouton exchange validate %>
    </div>
  </div>

  <% other_vinyle = @match.vinyle1.user != current_user ? @match.vinyle1 : @match.vinyle2 %>
  <% my_vinyle = @match.vinyle1.user == current_user ? @match.vinyle1 : @match.vinyle2 %>

  <div class="vinyles-container">
    <div class="vinyle vinyle-left">
      <%= link_to cl_image_tag(my_vinyle.photo.key, class: "match-bubble"), profile_path(my_vinyle.user_id) %>
    </div>
    <div class="vinyle vinyle-right">
      <%= link_to cl_image_tag(other_vinyle.photo.key, class: "match-bubble"), profile_path(other_vinyle.user_id) %>
    </div>
  </div>
  <% other_user = current_user == @match.vinyle1.user ? @match.vinyle2.user : @match.vinyle1.user %>
  <div class="container mt-3">
    <p class="text-center opacity-50">Échange <span class="fw-bold"><%= my_vinyle.title %></span> contre <span class="fw-bold"><%= other_vinyle.title %></span> avec <span class="fw-bold"><%= other_user.nickname %></span></p>
  </div>

  <div class="container chat">

    <%= turbo_stream_from "match_#{@match.id}_messages" %>
      <div id="messages" class="messages overflow-scroll">
        <% if @messages.any? %>
            <% @match.messages.each do |message| %>
              <%= render "messages/message", message: message, user: current_user %>
            <% end %>
        <% end %>
      </div>

      <%= simple_form_for [@match, @message],
        html: {class: "input-group",
        data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}} do |f|
      %>
        <% other_user = current_user == @match.vinyle1.user ? @match.vinyle1.user : @match.vinyle2.user %>
        <%= f.input :content,
  label: false,
  placeholder: "Organise l'échange...",
  input_html: { class: "form-control", style: "height: 20px; width: 100%; font-size: 15px; font-family: Poppins; font-style: italic;" },
  wrapper_html: { class: "form-control" } %>


        <%= button_tag(type: 'submit', class: 'input-group-text') do %>
          <i class="fa fa-2xl fa-paper-plane"></i>
        <% end %>
      <% end %>
  </div>
</div>

<%# TODO:  modal exchange validate %>
<div id="validateModal" class="modal fade" tabindex="-1" aria-labelledby="matchModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content text-center p-4" style="border-radius: 20px; background-color: #FFF2F3;">
      <a href="<%= profile_path(current_user) %>" class="btn-close position-absolute top-0 end-0 m-3" aria-label="Close"></a>
        <h1 style="font-size: 24px;">Side.B</h1>
        <h1 style="font-size: 30px;" class="mb-2">L'échange est validé !</h1>
        <p>Ajoute un autre vinyle ou continue d'échanger avec d'autres passionnés !</p>
      <div class="d-flex justify-content-center">
        <a href="<%= new_vinyle_path %>">
        <button class="btn-lavandia" style="height: 40px; width: 150px; font-size: 15px; font-family: Poppins;">Ajouter un vinyle</button>
        </a>
      </div>
    </div>
  </div>
</div>
<%# TODO:  modal exchange validate %>